include(":features:settings")
include(":libraries:core")
include(":features:activity")
include(":features:profile")
include(":features:details")
include(":features:bottomnavigation")
include(":features:discover")
include(":libraries:common-ui")
include(":features:login")
include(":libraries:data-domain")
include(":features:home")
include(":libraries:navigation")
include(":libraries:data")
include(":libraries:common")
include(":libraries:network")
include(":app")
rootProject.name = "Android Skeleton"