name: Build

on:
  # Trigger on every push to any branch except for master branch.
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Gradle
        id: build
        run: ./gradlew build
